# this is a new sub module inside ASC, may not need old dex infra
# Dex searcher cant reuse tinydex, because it need to load whole dex class def, method idx...
# so lazy parser may slow it down... 20260609
